### ISSUE TITLE
Suggestion: Make photos local when possible

### ISSUE THREAD

**Issue by mrand** [Judo-Documentation-Project/budotree#23]
Have you considered moving the photos local to budotree?   At least for the ones that seems to be publish domain-ish?

Just thinking about link rot.

**Comment by fsmunoz** [comment]
@mrand  I've partially addressed this in #32 , links are collected and scanned and there is a broken link report, plus instructions on the FAQ on how to fix them. I've kept the photo caching/location as a separate issue.

**Comment by fsmunoz** [comment]
Added a download step that updates the JSON with a local url, that when present is used in the page.

If remote images are broken then this will not work, but broken links should be fixed anyway (and are identified by the previous addition). An additional step to validate if the download is really an image can be added as an enhancement.
