### ISSUE TITLE
External link for a person

### ISSUE THREAD

**Issue by mrand** [Judo-Documentation-Project/budotree#40]
(I'm just opening issues as I think of things... not that I think they necessarily need to be addressed immediately! :)

I think there is huge value in being able to share a link externally that goes directly to an individual.  Perhaps the whole tree is still displayed, with either the person highlighted or the infobox summary displayed (or possibly both), although I could also see value in the link going to the filter to display just that persons direct line(s).

**Comment by fsmunoz** [comment]
That's very helpful - please open at will. 

That makes perfect sense: if I understood you correctly, you're talking about the ability to add something to the URL that would change the focus and the options. So, to start with, a simple `https://budotree.judoc.org?id=JDP-1` would select Kanō, and something like `https://budotree.judoc.org?id=JDP-1&focus=true` would show the view as if one had clicked on the "focus" button on the infobox, showing only related lines.

I think this can be split into two related features:

1. The ability to focus on someone using an URL
2. The ability to control display options through URL parameters


PS: If you don't have any strong objection I can add you to the parent organisation (not that it changes anything for now, but you've already participated enough for it to make sense, and it carries no obligation at all).

**Comment by mrand** [comment]
Yes, something like that.
The main thing I was suggesting a link/share button somewhere (presumably
in the infobox) to generate the URL.

Feel free to add me to the parent organization.  I have a wide variety of
interests, but happy to help on this.

**Comment by fsmunoz** [comment]
This should tackle the main feature request, although some aspects can be improved (e.g., I think that the footer is the right place to do it and that the icon works, but I can imagine other scenarios in which clicking copies to clipboard for example).

The rest should be addressed in a separate issue about determining visualisation options through query parameters, after which we can determine if this new button should automatically add any.
